disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Deep Spark"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "Graphics software engineering â€” real-time rendering notes, GPU experiments, and performance analysis."
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Pawel Stolecki"
  headline = "Rendering Engineer"
  # image = "images/author.jpg"
  links = [
    { x-twitter = "https://x.com/stoleckipawel" },
    { linkedin = "https://www.linkedin.com/in/stoleckipawel/" },
    { youtube = "https://www.youtube.com/@stoleckipawel" },
  ]